#!/usr/bin/env bash
#
# Bootstrap the Terraform remote-state backend for the CURRENT AWS account.
#
# Derives the account id from your active AWS credentials (nothing hardcoded),
# then creates a versioned + encrypted + private S3 bucket to hold the Terraform
# state, writes backend.hcl (git-ignored), and wires this working directory to it.
#
# Safe to re-run, and safe on a workspace that already has state:
#   * first run with EXISTING LOCAL state  -> migrates that state into S3
#     (so a stack you already applied locally is preserved, not orphaned)
#   * already pointing at this bucket      -> re-points, state untouched
#   * fresh workspace                      -> plain init
#
# Usage:
#   ./bootstrap-state.sh
#
# Optional overrides (env vars):
#   AWS_REGION / AWS_DEFAULT_REGION   state bucket region   (default us-east-1)
#   STATE_NAME                        bucket infix          (default multiagent-orchestrator)
#                                     -> bucket = agentcore-<STATE_NAME>-tfstate-<account>
#
set -euo pipefail
cd "$(dirname "$0")"

REGION="${AWS_REGION:-${AWS_DEFAULT_REGION:-us-east-1}}"
NAME="${STATE_NAME:-multiagent-orchestrator}"

# --- Derive the account id from the caller's credentials -------------------
ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text 2>/dev/null || true)"
if [[ -z "$ACCOUNT_ID" || "$ACCOUNT_ID" == "None" ]]; then
  echo "ERROR: could not resolve your AWS account. Check your credentials:" >&2
  echo "       aws sts get-caller-identity" >&2
  exit 1
fi

BUCKET="agentcore-${NAME}-tfstate-${ACCOUNT_ID}"
echo "Account : ${ACCOUNT_ID}"
echo "Region  : ${REGION}"
echo "Bucket  : ${BUCKET}"
echo

# --- Create the bucket (idempotent) ----------------------------------------
if aws s3api head-bucket --bucket "$BUCKET" 2>/dev/null; then
  echo "Bucket already exists — reusing it."
else
  echo "Creating bucket..."
  if [[ "$REGION" == "us-east-1" ]]; then
    # us-east-1 must NOT be sent a LocationConstraint.
    aws s3api create-bucket --bucket "$BUCKET" --region us-east-1 >/dev/null
  else
    aws s3api create-bucket --bucket "$BUCKET" --region "$REGION" \
      --create-bucket-configuration "LocationConstraint=${REGION}" >/dev/null
  fi
fi

echo "Enabling versioning, encryption, and public-access block..."
aws s3api put-bucket-versioning --bucket "$BUCKET" \
  --versioning-configuration Status=Enabled
aws s3api put-bucket-encryption --bucket "$BUCKET" \
  --server-side-encryption-configuration \
  '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"},"BucketKeyEnabled":true}]}'
aws s3api put-public-access-block --bucket "$BUCKET" \
  --public-access-block-configuration \
  BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true

# --- Write the backend config Terraform reads at init time -----------------
cat > backend.hcl <<EOF
# Generated by bootstrap-state.sh — git-ignored, per-account. Do not commit.
bucket = "${BUCKET}"
region = "${REGION}"
EOF
echo "Wrote backend.hcl"
echo

# --- Wire the working directory to this backend ----------------------------
# If there is real LOCAL state here that has not been migrated yet, migrate it
# (never -reconfigure, which would abandon it and orphan live resources).
LOCAL_RESOURCES=0
if [[ -f terraform.tfstate ]]; then
  LOCAL_RESOURCES="$(python3 -c "import json,sys;print(len(json.load(open('terraform.tfstate')).get('resources',[])))" 2>/dev/null || echo 0)"
fi

if [[ "$LOCAL_RESOURCES" -gt 0 ]]; then
  echo "Found local state with ${LOCAL_RESOURCES} resource(s) — MIGRATING it to S3."
  cp terraform.tfstate "terraform.tfstate.pre-migrate.$(date +%Y%m%d%H%M%S).backup"
  terraform init -backend-config=backend.hcl -migrate-state -force-copy
else
  echo "Running terraform init..."
  terraform init -backend-config=backend.hcl -reconfigure
fi

echo
echo "Done. Remote state is ready for account ${ACCOUNT_ID}."
echo "Verify with: terraform plan   (expect 'No changes' on an already-applied stack)"
echo "Next:        terraform apply"
